baseurl = "https://www.chatpress.co.uk/"
languageCode = "en-gb"
title = "The ChatPress"
description = "Random thoughts about sport, politics and global affairs"
preserveTaxonomyNames = true
disableKinds = ["taxonomyTerm"]
[outputs]
  page = ["HTML", "AMP"]
[permalinks]
  post = "/:slug/"
  tags = "/tag/:slug/"
[params]
  mainSections = ["politics", "sport"]
 [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 
